name: Create d2m PR

on:
  push:
    branches:
      - develop

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  d2m-pr:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Ruby 3.3.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.1
      - name: Execute gir-pr-develop (develop -> main)
        env:
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gem install git-pr-release
          git-pr-release || echo "Done."
